package service

// RoleSuggestions is a curated list of common job role titles.
// Used by the typeahead on the frontend and as the canonical source for
// target-role-driven job searches.
var RoleSuggestions = []string{
	// ── Software Engineering ──────────────────
	"Software Engineer",
	"Senior Software Engineer",
	"Staff Software Engineer",
	"Principal Software Engineer",
	"Software Architect",
	"Full Stack Developer",
	"Full Stack Engineer",
	"Frontend Developer",
	"Frontend Engineer",
	"Backend Developer",
	"Backend Engineer",
	"Web Developer",
	"Mobile Developer",
	"iOS Developer",
	"Android Developer",
	"React Developer",
	"React Native Developer",
	"Angular Developer",
	"Vue.js Developer",
	"Node.js Developer",
	"Python Developer",
	"Java Developer",
	"Go Developer",
	"Rust Developer",
	"Ruby Developer",
	"PHP Developer",
	".NET Developer",
	"C++ Developer",
	"Embedded Software Engineer",
	"Firmware Engineer",
	"Systems Engineer",
	"Platform Engineer",
	"API Developer",
	"Microservices Engineer",

	// ── DevOps / Infrastructure ──────────────
	"DevOps Engineer",
	"Site Reliability Engineer",
	"SRE",
	"Cloud Engineer",
	"Cloud Architect",
	"Infrastructure Engineer",
	"Platform Engineer",
	"Release Engineer",
	"Build Engineer",
	"Systems Administrator",
	"Network Engineer",
	"Security Engineer",
	"DevSecOps Engineer",
	"Kubernetes Engineer",
	"AWS Solutions Architect",

	// ── Data ─────────────────────────────────
	"Data Engineer",
	"Data Scientist",
	"Data Analyst",
	"Machine Learning Engineer",
	"ML Engineer",
	"AI Engineer",
	"AI/ML Engineer",
	"Deep Learning Engineer",
	"NLP Engineer",
	"Computer Vision Engineer",
	"Business Intelligence Analyst",
	"Analytics Engineer",
	"Data Architect",
	"Database Administrator",
	"ETL Developer",
	"Big Data Engineer",

	// ── Product / Design ─────────────────────
	"Product Manager",
	"Senior Product Manager",
	"Product Owner",
	"Technical Product Manager",
	"Product Designer",
	"UX Designer",
	"UI Designer",
	"UX/UI Designer",
	"UX Researcher",
	"Interaction Designer",
	"Visual Designer",
	"Graphic Designer",
	"Design Lead",
	"Creative Director",
	"Brand Designer",
	"Motion Designer",

	// ── QA / Testing ─────────────────────────
	"QA Engineer",
	"Quality Assurance Engineer",
	"SDET",
	"Test Automation Engineer",
	"QA Analyst",
	"Performance Engineer",

	// ── Management / Leadership ──────────────
	"Engineering Manager",
	"Senior Engineering Manager",
	"VP of Engineering",
	"Director of Engineering",
	"CTO",
	"Technical Lead",
	"Tech Lead",
	"Team Lead",
	"Scrum Master",
	"Agile Coach",
	"Program Manager",
	"Technical Program Manager",
	"Project Manager",

	// ── Cybersecurity ────────────────────────
	"Cybersecurity Analyst",
	"Security Analyst",
	"Penetration Tester",
	"Security Architect",
	"Information Security Engineer",
	"SOC Analyst",
	"Threat Intelligence Analyst",
	"Application Security Engineer",
	"Cloud Security Engineer",
	"GRC Analyst",

	// ── Blockchain / Web3 ───────────────────
	"Blockchain Developer",
	"Smart Contract Developer",
	"Solidity Developer",
	"Web3 Developer",

	// ── IT / Support ────────────────────────
	"IT Support Specialist",
	"Help Desk Technician",
	"Desktop Support Engineer",
	"IT Manager",
	"IT Director",
	"Solutions Architect",
	"Technical Support Engineer",
	"Solutions Engineer",
	"Implementation Engineer",

	// ── Sales / Marketing (Tech) ────────────
	"Sales Engineer",
	"Solutions Consultant",
	"Pre-Sales Engineer",
	"Technical Account Manager",
	"Customer Success Manager",
	"Customer Success Engineer",
	"Growth Engineer",
	"Marketing Technologist",
	"SEO Specialist",
	"Digital Marketing Manager",
	"Content Strategist",

	// ── Technical Writing / Docs ─────────────
	"Technical Writer",
	"Documentation Engineer",
	"Developer Advocate",
	"Developer Relations Engineer",
	"Developer Experience Engineer",

	// ── Finance / Business ───────────────────
	"Financial Analyst",
	"Business Analyst",
	"Systems Analyst",
	"Quantitative Analyst",
	"Quantitative Developer",
	"Risk Analyst",

	// ── Game Development ─────────────────────
	"Game Developer",
	"Game Designer",
	"Game Programmer",
	"Unity Developer",
	"Unreal Engine Developer",
	"Gameplay Engineer",

	// ── Hardware / Electronics ────────────────
	"Hardware Engineer",
	"Electrical Engineer",
	"FPGA Engineer",
	"ASIC Design Engineer",
	"Robotics Engineer",
	"IoT Engineer",

	// ── Research ──────────────────────────────
	"Research Scientist",
	"Research Engineer",
	"Applied Scientist",
	"Computer Scientist",
}
